/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Jframes;

import java.sql.*;
import javax.swing.JOptionPane;
import sistemarestaurante.*;

/**
 *
 * @author DURAN y harry
 */
public class Login extends javax.swing.JFrame {

    InicioSesion in = new InicioSesion(); // nuevo objeto InicioSesion
    Menu m = new Menu(); // nuevo objeto Menu

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        usuarioLabel = new javax.swing.JLabel();
        contraseniaLabel = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtClave = new javax.swing.JPasswordField();
        btnIngresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio de Sesion");
        setMinimumSize(new java.awt.Dimension(960, 580));
        setResizable(false);
        setSize(new java.awt.Dimension(960, 580));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        Titulo.setText("INICIO DE SESIÓN");
        jPanel1.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        usuarioLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        usuarioLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usuarioLabel.setText("USUARIO");
        jPanel1.add(usuarioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 430, -1));

        contraseniaLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        contraseniaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contraseniaLabel.setText("CONTRASEÑA");
        jPanel1.add(contraseniaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 430, -1));

        txtUsuario.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 430, 50));

        txtClave.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtClave.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 430, 50));

        btnIngresar.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnIngresar.setText("INGRESAR");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 250, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        String usuario = txtUsuario.getText();// Guardamos el usuario
        String clave = txtClave.getText();// Guardamos la contraseña
        in.IniciarSesion(usuario, clave); // metodo para iniciar sesion
        boolean encontrado = in.encontrado; // nos guarda el valor retornado
        if (encontrado == true) { // si encontro el usuario y la contraseña ingresada
            this.setVisible(false);// apagamos este jframe
            m.setVisible(true); // encendemos el jframe menu
            m.setLocationRelativeTo(null); // centramos el menu
        } else { // si no encuentra la clave y usuario
            JOptionPane.showMessageDialog(null, "USUARIO/CONTRASEÑA INVALIDOS. ", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    /**
         * @param args the command line arguments
         */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel contraseniaLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JLabel usuarioLabel;
    // End of variables declaration//GEN-END:variables
}
