/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Jframes;

/**
 *
 * @author plast
 */
public class Salon extends javax.swing.JFrame {

    /**
     * Creates new form Salon
     */
    public Salon() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelPrincipal = new javax.swing.JPanel();
        JPanelBotones = new javax.swing.JPanel();
        btnMesa1 = new javax.swing.JButton();
        btnMesa2 = new javax.swing.JButton();
        btnMesa3 = new javax.swing.JButton();
        btnMesa4 = new javax.swing.JButton();
        btnMesa5 = new javax.swing.JButton();
        btnMesa6 = new javax.swing.JButton();
        btnMesa7 = new javax.swing.JButton();
        btnMesa8 = new javax.swing.JButton();
        btnMesa9 = new javax.swing.JButton();
        btnMesa10 = new javax.swing.JButton();
        btnMesa11 = new javax.swing.JButton();
        btnMesa12 = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        imagenDeFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(960, 580));

        JPanelPrincipal.setMaximumSize(new java.awt.Dimension(960, 580));
        JPanelPrincipal.setMinimumSize(new java.awt.Dimension(960, 580));
        JPanelPrincipal.setPreferredSize(new java.awt.Dimension(960, 580));
        JPanelPrincipal.setLayout(null);

        JPanelBotones.setOpaque(false);
        JPanelBotones.setLayout(new java.awt.GridLayout(3, 3, 10, 10));

        btnMesa1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnMesa1.setText("Mesa 1");
        btnMesa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMesa1ActionPerformed(evt);
            }
        });
        JPanelBotones.add(btnMesa1);

        btnMesa2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnMesa2.setText("Mesa 2");
        btnMesa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMesa2ActionPerformed(evt);
            }
        });
        JPanelBotones.add(btnMesa2);

        btnMesa3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnMesa3.setText("Mesa 3");
        JPanelBotones.add(btnMesa3);

        btnMesa4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnMesa4.setText("Mesa 4");
        JPanelBotones.add(btnMesa4);

        btnMesa5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnMesa5.setText("Mesa 5");
        JPanelBotones.add(btnMesa5);

        btnMesa6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnMesa6.setText("Mesa 6");
        JPanelBotones.add(btnMesa6);

        btnMesa7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnMesa7.setText("Mesa 7");
        JPanelBotones.add(btnMesa7);

        btnMesa8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnMesa8.setText("Mesa 8");
        JPanelBotones.add(btnMesa8);

        btnMesa9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnMesa9.setText("Mesa 9");
        JPanelBotones.add(btnMesa9);

        btnMesa10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnMesa10.setText("Mesa 10");
        JPanelBotones.add(btnMesa10);

        btnMesa11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnMesa11.setText("Mesa 11");
        JPanelBotones.add(btnMesa11);

        btnMesa12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnMesa12.setText("Mesa 12");
        JPanelBotones.add(btnMesa12);

        JPanelPrincipal.add(JPanelBotones);
        JPanelBotones.setBounds(70, 90, 790, 350);

        titulo.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        titulo.setText("Salon (Mesas del Restaurante)");
        JPanelPrincipal.add(titulo);
        titulo.setBounds(20, 20, 520, 47);

        btnVolver.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnVolver.setText("Volver");
        JPanelPrincipal.add(btnVolver);
        btnVolver.setBounds(340, 460, 250, 60);

        imagenDeFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/icono3.jpg"))); // NOI18N
        imagenDeFondo.setMaximumSize(new java.awt.Dimension(960, 580));
        imagenDeFondo.setMinimumSize(new java.awt.Dimension(960, 580));
        imagenDeFondo.setPreferredSize(new java.awt.Dimension(960, 580));
        JPanelPrincipal.add(imagenDeFondo);
        imagenDeFondo.setBounds(0, 0, 960, 580);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 944, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 541, Short.MAX_VALUE)
        );

        setBounds(0, 0, 960, 580);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMesa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMesa1ActionPerformed
        // TODO add your handlingasdasd code here:
    }//GEN-LAST:event_btnMesa1ActionPerformed

    private void btnMesa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMesa2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMesa2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Salon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Salon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Salon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Salon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Salon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelBotones;
    private javax.swing.JPanel JPanelPrincipal;
    private javax.swing.JButton btnMesa1;
    private javax.swing.JButton btnMesa10;
    private javax.swing.JButton btnMesa11;
    private javax.swing.JButton btnMesa12;
    private javax.swing.JButton btnMesa2;
    private javax.swing.JButton btnMesa3;
    private javax.swing.JButton btnMesa4;
    private javax.swing.JButton btnMesa5;
    private javax.swing.JButton btnMesa6;
    private javax.swing.JButton btnMesa7;
    private javax.swing.JButton btnMesa8;
    private javax.swing.JButton btnMesa9;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel imagenDeFondo;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
